export const Page = () => {


    return (
        <>
        <h1 className="text-3xl font-bold">Hello, world!</h1>
        <p className="text-lg">Welcome to your new Telefunc app.</p>
        <p className="text-lg">This is a page generated by Telefunc.</p>
        </>
    );
}